export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const CITY_DELETED = 'CITY_DELETED';
export const KELVIN_TOGGLE = 'KELVIN_TOGGLE';
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'