export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const CITY_DELETED = 'CITY_DELETED';
export const CITY_UPDATE = 'CITY_UPDATE';
export const SET_WEATHER = 'SET_WEATHER';